### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Katarzina** [apertureless/vue-cookie-law#19]
### vue & vue-cookie-law version
2.0.x, x.y.z

### What is actually happening?
nuxt 

`<template>`
`<footer>`
     `<div class="wrapper dark-gray `no-padding">`        
```
 
 
 <cookie-law theme="dark-lime"></cookie-law>
    </div>
</footer>

</template>

<script>
import CookieLaw from 'vue-cookie-law';

export default {
  components: {
    CookieLaw
  }
}

</script>

```

I'v got:
Nuxt.js Error:

ReferenceError: document is not defined
    at addStyle (/var/www/vue/node_modules/vue-cookie-law/dist/vue-cookie-law.js:579:22)

**Comment by apertureless** [comment]
Hey @Katarzina 

Mh yeah I guess this is a common thing for plugins that are working only in the browser. There are some guides in the nuxt.js docs on how to disable ssr for certain plugins.

https://nuxtjs.org/guide/plugins/#client-side-only

I guess that the localStorage stuff is making some trouble here.

**Comment by Katarzina** [comment]
thank you...your advice has helped

**Comment by indifisher** [comment]
I've just run into this exact issue. @Katarzina please, can you let me know how you resolved this?

**Comment by indifisher** [comment]
Fixed in nuxt by wrapping in `<no-ssr></no-ssr>`!

**Comment by anvlkv** [comment]
Or event better with [vue-client-only](https://www.npmjs.com/package/vue-client-only) `<client-only></client-only>`

Sorry got instantly fed up with nuxt's too much magic(TM)
