### ISSUE TITLE
Could you make message set as v-html and not {{...}} 

### ISSUE THREAD

**Issue by paulgeisler** [apertureless/vue-cookie-law#20]
### vue & vue-cookie-law version
2.3.1, 1.1.0

### What is actually happening?

I try to create a content with a `router-link` inside it but it needs to be set as v-html to work properly.
Or you could work with `<slot>` for the content.

**Comment by apertureless** [comment]
Hey sorry for the late reply. Missed the notification on that one oO

Yeah I like the idea with slots. It would give people more power of the content.

I will implement it.

**Comment by apertureless** [comment]
Implemented in version 1.2.0
