### ISSUE TITLE
not set buttonText 

### ISSUE THREAD

**Issue by allfreelancers** [apertureless/vue-cookie-law#24]
### vue & vue-cookie-law version
vue-cookie-law version - last

not set buttonText 

buttonText="'test'" not work

**Comment by apertureless** [comment]
Well can you provide a reproduction?
It is working for me

https://codepen.io/apertureless/pen/RLOjRR

**Comment by allfreelancers** [comment]
@apertureless  sorry I use:

buttonText="Click"

**Comment by apertureless** [comment]
Yeah but in Vue.js all camelCase props need to be written out as kebab-case with `-` between them.
