### ISSUE TITLE
Can not close the cookie message in Safari, iPhone 5C

### ISSUE THREAD

**Issue by bobcat1** [apertureless/vue-cookie-law#25]
### vue & vue-cookie-law version
vue: 2.5.2
vue-cookie-law: 1.3.0

### Steps to reproduce
On an iPhone 5C, iOS version 10.3.3, using Safari 602.1, AppleWebKit/603.3.8:
1. Open a webpage which uses vue-cookie-law
2. Try to click on the "Got it" button to close it

### What is Expected?
The message disappears

### What is actually happening?
The message persists, nothing happens when "Got it" is clicked.

It seems to be working on certain other iPhone and iPad devices that I have had the chance to try, but unfortunately not on the 5C.

**Comment by apertureless** [comment]
Mh does a error get thrown in the console?
