### ISSUE TITLE
Detect Component status

### ISSUE THREAD

**Issue by menteora** [apertureless/vue-cookie-law#26]
Hi, thank you very much for your component. 

I've a question.
There's a way to watch the status of cookies inside localstorage or with a component specific feature?
We have `opt-in` clause and we must disable the component that require cookies (facebook comments, etc ...) until we'll press the cookie bar button.

For example:
`<facebook-comments v-if="cookieStatus"></facebook-comments>`

thanks

**Comment by menteora** [comment]
Hi @apertureless , thank you very much for your attention and sorry for my english.

I think there's two use-case: 
1. The user opens a new page and the cookie bar is open or close, based on localstorage. In this case your plugin just works perfectly.

2. The user click "accept" on cookie bar, in this case I must reload the page to trigger event that read inside localstorage and visualize facebook-comments.

I think that your _first_ solution work!

I've simutated this workflow putting a button inside cookie law bar and vuex.

**CookieLawFooter.vue**
```html
<template>
  <footer>
    <cookie-law theme="dark-lime" buttonText="accept">
        <div slot="message">
          <button v-on:click="$store.commit('acceptCookie')">click here to accept cookie</button>
          long message<router-link to="policy">read more</router-link>
        </div>
    </cookie-law>
  </footer>
</template>
```
**FacebookComments.vue**
```html
<template>
  <div>
    <h1 v-if="$store.state.isCookieAccepted" >{{$store.state.isCookieAccepted}} great work!</h1>
    <h1 v-else>{{$store.state.isCookieAccepted}} what the hell!</h1>
  </div>
</template>

<script>
  export default {
    created () {
      this.$store.commit('setCookieStatus')
    }
  }
</script>
```
**nuxt store/index.js**
```javascript
export const state = () => ({
  isCookieAccepted: false
})

//not useful, this solution not work in real time
export const getters = {
  cookieStatus: state => {
    return localStorage.getItem('cookie:accepted') || false
  }
}

export const mutations = {
  acceptCookie (state) {
    state.isCookieAccepted = true
  },
  setCookieStatus (state) {
    state.isCookieAccepted = localStorage.getItem('cookie:accepted') || false
  }
}
```
**plugins/vue-cookie-law.js**
Facebook comments use indirectly localstorage with `setCookieStatus`, it must be `ssr-false` for nuxt

```javascript
import Vue from 'vue'
import CookieLaw from 'vue-cookie-law'
import FacebookComments from '~/components/FacebookComments.vue'

Vue.component('cookie-law', CookieLaw)
Vue.component('facebook-comments', FacebookComments)
```
**nuxt.config.js**
```
plugins: [{src: '~plugins/vue-cookie-law.js', ssr: false} ],
```
Correct me if I'm wrong.

**Comment by apertureless** [comment]
Released with version `1.4.0`

**Comment by menteora** [comment]
To be thorough, I switched to `vue-no-ssr` for only-client rendering.
In my opinion is better for clearness and I don't have strange behaviors than first nuxtjs plugin solution.

Thank you very much for your support!
L.

**Comment by apertureless** [comment]
Yeah, I wanted to work on some better ssr integrations as nuxt seems to be pretty popular lateley.
