### ISSUE TITLE
Improve ssr

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-cookie-law#30]
- Adding ssr build
- Utilize `Vue.use()` #28 so you can `ssr: false` in nuxt.

**Comment by remoe** [comment]
Currently it's possible to use https://github.com/egoist/vue-no-ssr

**Comment by apertureless** [comment]
@remoe 
Yeah, there is also no way around it. Because nuxt does not like the `appear` transition.

**Comment by marcuskourie** [comment]
@apertureless has this been implemented? Would love to use it on a nuxt project and struggling to get it setup.

**Comment by apertureless** [comment]
@marcuskourie 
There will be no ssr build, as it's not possible to produce a proper ssr build because of the `appear` transitions.

However, it works fine together with vue-no-ssr. 

I have it running in various production projects with this setup.

**Comment by sebastianjung** [comment]
vue-no-ssr does not seem to work for me.

i used it like so:
```
<ClientOnly>
      <cookie-law theme="dark-lime" button-text="Ok">
        <div slot="message">
          Diese Seite verwendet Cookies, um Ihnen eine optimale Nutzung zu
          ermöglichen. Durch die weitere Nutzung der Website stimmen Sie der
          Verwendung von Cookies zu. Weitere Informationen finden Sie in unserer
          Datenschutzerklärung.
          <router-link to="datenschutz" class="color-2"
            >Hier klicken</router-link
          >
        </div>
      </cookie-law>
</ClientOnly>
```


And added the package in a plugin file
```
import Vue from 'vue'
import CookieLaw from 'vue-cookie-law'

Vue.mixin({
  components: {
    CookieLaw
  }
})

```

```
  plugins: [
   ...
    { src: '~/plugins/vue-cookie-law.js' },
   ...
  ],
```

Any advice?

**Comment by sebastianjung** [comment]
it seems with the native no-ssr-Tag of Nuxt instead of the client-only-tag from 'vue-client-only' it seems to work... Might be i am missing something here..

EDIT: Doesn't work.

**Comment by apertureless** [comment]
Don't really understand your last comment.
There is btw no real need to add it as a plugin. It should be enough to just import it as a component into your `layouts/default.vue`. It would make only sense to add it as a global plugin if you're using multiple different layouts.

```vue
// layouts/default.vue

<template>
  <div>
    <navigation-header />
    <nuxt />
    <page-footer />

    <no-ssr>
      <cookie-law
        button-text="Accept!"
        button-class="button"
      >
        <div slot="message">
          Custom text
          <a
            href="/datenschutz/"
            target="_blank"
          >More info.</a>
        </div>
      </cookie-law>
    </no-ssr>
</template>

<script>

const CookieLaw = () => import(/* webpackChunkName: 'vue-cookie-law' */'vue-cookie-law')

export default {
  components: { NavigationHeader, PageFooter, CookieLaw }
 
}
</script>
```

**Comment by sebastianjung** [comment]
you are absolutely right. i'm not sure why i implemented it this way to be honest. Maybe i was trying to do the ssr: false thingy :/

Still doesn't work with nossr, though. Its hanging in an infinite reloading loop.


EDIT: It seems my chrome is buggy. Running it as `npm run generate` from my server fixes the problem in chrome.

So what finally worked for me 🚀:

```
<no-ssr>
      <cookie-law theme="dark-lime" button-text="Ok">
        bla
      </cookie-law>
</no-ssr>
```

and in the script tag:
```
const CookieLaw = () => import('vue-cookie-law')
export default {
  components: {
    CookieLaw
  }
}
```

@apertureless Thank you for your advice. Appreciate it!

**Comment by apertureless** [comment]
Oh yeah sorry forgot to change that. The package was renamed to vue-client-only.
Thus you also need to 

```js
import ClientOnly from 'vue-client-only'

```

and then

```html
<client-only>
	<cookie-law>stuff</cookie-law>
</client-only>
```
