### ISSUE TITLE
localStorage is not available in iOS Safari private mode in iOS < 11. Throws error.

### ISSUE THREAD

**Issue by tomvo** [apertureless/vue-cookie-law#33]
### vue & vue-cookie-law version
1.4

### Reproduction Link
https://codepen.io/apertureless/pen/RLOjRR

### Steps to reproduce
1. Open iOS Sim or iOS device with iOS 10.x
2. Open an incognito safari window with an application containing vue-cookie-law or just this pen https://codepen.io/apertureless/pen/RLOjRR
3. Check the console
4. See the Quota Exceeded error being triggered when clicking the accept cookie button.

### What is Expected?
No errors.

### What is actually happening?
iOS < 11, Safari in private mode does not support localstorage. We should try to add a test and a cookie fallback.

Possible test:

```
try {
    const test = '__vue-cookielaw-check-localStorage'

    window.localStorage.setItem(test, test)
    window.localStorage.removeItem(test)
} catch (e) {
    console.error('Local storage is not supported')
}
```

**Comment by tomvo** [comment]
Also please check this PR for a fix: https://github.com/apertureless/vue-cookie-law/pull/34

**Comment by apertureless** [comment]
Thanks for the issue. I will check it out and thanks for your PR. Will review it ASAP. 👍

**Comment by tomvo** [comment]
Awesome! Do you think you have some time soon? We’re seeing a lot of errors on this in production.

**Comment by apertureless** [comment]
New release is live
