### ISSUE TITLE
Hide banner after some timeout

### ISSUE THREAD

**Issue by Kinzi** [apertureless/vue-cookie-law#37]
Is there anyway to hide the banner programmatically? Like after changing routes or with a setTimeout?

I tried setTimeout with `v-if="showBanner"` or `:class="{'invisible': !showBanner}"` but it didn't work. 

Any idea?

**Comment by apertureless** [comment]
Right now there is no way of hiding it.
But could be easily added over a prop.

**Comment by urbantrout** [comment]
I created a PR where you could make use of the scoped slot and its `close` method. See #42
