### ISSUE TITLE
More slots.

### ISSUE THREAD

**Issue by MaverickMartyn** [apertureless/vue-cookie-law#38]
### vue & vue-cookie-law version
2.0.x, x.y.z

This is a feature request.
I would love to see this with mores slots, as I use Vuetify as my CSS/components framework of choice.
Slots for buttons and so on, other than "message", would allow me to continue using those components.
Thank you for your great work so far. :)

**Comment by urbantrout** [comment]
I created a pull request #42

**Comment by apertureless** [comment]
`scoped-slot` support released in version `1.8.0`
