### ISSUE TITLE
How to setup domain for cookie?

### ISSUE THREAD

**Issue by faizaajmal** [apertureless/vue-cookie-law#48]
i want to setup domain name for the cookie? how can i do that?

**Comment by apertureless** [comment]
It is currently not supported.
But as it is using [tiny-cookie](https://github.com/Alex1990/tiny-cookie) in the back for the cookie provider, it should be easy to pass the options to the `setCookie()` method.

**Comment by SevenIndirecto** [comment]
Hey, I opened a PR for this issue https://github.com/apertureless/vue-cookie-law/pull/54
