### ISSUE TITLE
cookie name

### ISSUE THREAD

**Issue by funkysoul** [apertureless/vue-cookie-law#55]
### vue & vue-cookie-law version
2.0.x, latest

### Reproduction Link

no need

### Steps to reproduce
no need

### What is Expected?
It would be great to have the option of defining the cookiename instead of only "cookie:accepted"

### What is actually happening?
no need

**Comment by lucas-barros** [comment]
Seems like there is a prop called `storageName` that does that, but is not documented, right?

**Comment by funkysoul** [comment]
@lucas-barros true that.
@apertureless mind updating the docs for future reference?

**Comment by apertureless** [comment]
Yop its updated ✌️
