### ISSUE TITLE
Can you call the open() method or modify isOpen

### ISSUE THREAD

**Issue by Buscedv** [apertureless/vue-cookie-law#69]
Can you either call the open() method from ex. a button click in another component, or can you directly modify the isOpen data property from another component? Basically I want a button in my site's footer that re-opens the consent banner so that the user can choose "Accept" or "Decline" later on again.

**Comment by apertureless** [comment]
You can either call it directly, if you attach the `ref` attribute on the component.

```html
<cookie-law ref="cookie"> </cookie-law>
```
And call it like this:

```js
this.$refs.cookie.open()
```

Which is a fast but *dirty* solution as it introduces quite tight coupling between the parent and child component.

Another way would be to use an event bus.

https://stackoverflow.com/questions/40957008/how-to-access-to-a-child-method-from-the-parent-in-vue-js

**Comment by Buscedv** [comment]
Thank you!
